# Generated by Django 5.2.15 on 2026-07-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eway_bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewaybillrecord',
            name='be_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ewaybillrecord',
            name='extraction_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ewaybillrecord',
            name='extraction_raw_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ewaybillrecord',
            name='validation_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='ewaybillrecord',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('needs_review', 'Needs Review'), ('verified', 'Verified'), ('extraction_failed', 'Extraction Failed')], default='processing', max_length=50),
        ),
    ]
