# Generated by Django 5.2.15 on 2026-06-30 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firms', '0001_initial'),
        ('invoices', '0004_bill_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudVaultEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=1000)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_entries', to='invoices.bill')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_entries', to='firms.firm')),
            ],
        ),
    ]
