# Generated by Django 5.2.15 on 2026-06-30 09:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_excelexportbatch'),
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudvaultentry',
            name='excel_export',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_entries', to='invoices.excelexportbatch'),
        ),
        migrations.AddField(
            model_name='cloudvaultentry',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cloudvaultentry',
            name='module',
            field=models.CharField(choices=[('invoices', 'Invoices'), ('exports', 'Excel Exports'), ('import_export', 'Import-Export Customs'), ('eway_bills', 'E-Way Bills')], default='invoices', max_length=50),
        ),
        migrations.AddField(
            model_name='cloudvaultentry',
            name='uploaded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
