# Generated by Django 5.2.15 on 2026-06-30 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_docs', '0001_initial'),
        ('vault', '0002_cloudvaultentry_excel_export_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudvaultentry',
            name='trade_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_entries', to='trade_docs.importexportrecord'),
        ),
    ]
