# Generated by Django 4.2.30 on 2026-06-30 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eway_bills', '0001_initial'),
        ('vault', '0003_cloudvaultentry_trade_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudvaultentry',
            name='eway_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_entries', to='eway_bills.ewaybillrecord'),
        ),
    ]
