# Generated by Django 5.1.15 on 2026-08-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_cloudvaultentry_eway_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudvaultentry',
            name='module',
            field=models.CharField(choices=[('invoices', 'Invoices'), ('exports', 'Excel Exports'), ('import_export', 'Import-Export Customs'), ('eway_bills', 'E-Way Bills'), ('documents', 'Documents')], default='invoices', max_length=50),
        ),
    ]
