# Generated by Django 5.2.15 on 2026-06-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='extraction_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='extraction_raw_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='validation_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('needs_review', 'Needs Review'), ('approved', 'Approved'), ('extraction_failed', 'Extraction Failed')], default='processing', max_length=50),
        ),
    ]
