# Generated by Django 5.2.15 on 2026-06-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_bill_extraction_failed_bill_extraction_raw_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('needs_review', 'Needs Review'), ('verified', 'Verified'), ('approved', 'Approved'), ('extraction_failed', 'Extraction Failed')], default='processing', max_length=50),
        ),
    ]
