# Generated by Django 5.2.15 on 2026-06-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
