# Generated by Django 5.1.15 on 2026-08-19 09:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eway_bills', '0002_ewaybillrecord_be_number_and_more'),
        ('firms', '0001_initial'),
        ('invoices', '0005_excelexportbatch'),
        ('trade_docs', '0002_alter_importexportrecord_container_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('gstin', models.CharField(blank=True, default='', max_length=15)),
                ('pan', models.CharField(blank=True, default='', max_length=10)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='firms.firm')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('snapshot_date', models.DateField()),
                ('total_receivables', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_payables', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net_cash_flow', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('overdue_receivables', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('overdue_payables', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('open_risk_signals', models.PositiveIntegerField(default=0)),
                ('health_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0–100 composite score.', max_digits=5)),
                ('cashflow_forecast', models.JSONField(blank=True, default=dict, help_text='AI-generated forecast payload.')),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='Detailed category breakdowns.')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='firms.firm')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('txn_type', models.CharField(choices=[('invoice', 'Invoice'), ('payment', 'Payment'), ('purchase_order', 'Purchase Order'), ('bank_transaction', 'Bank Transaction'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note')], max_length=30)),
                ('direction', models.CharField(choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('partially_matched', 'Partially Matched'), ('fully_matched', 'Fully Matched'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference_number', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('txn_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='invoices.bill')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='intelligence.customer')),
                ('eway_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='eway_bills.ewaybillrecord')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='firms.firm')),
                ('trade_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='trade_docs.importexportrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_group', models.UUIDField(db_index=True, help_text='Groups related links into one reconciliation set.')),
                ('match_confidence', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='0.0000–1.0000 confidence score.', max_digits=5)),
                ('match_method', models.CharField(choices=[('manual', 'Manual'), ('rule_based', 'Rule-Based'), ('ai_suggested', 'AI-Suggested')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='firms.firm')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('matched_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_reconciliation_links', to='intelligence.transaction')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_links', to='intelligence.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('gstin', models.CharField(blank=True, default='', max_length=15)),
                ('pan', models.CharField(blank=True, default='', max_length=10)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='firms.firm')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='intelligence.vendor'),
        ),
        migrations.CreateModel(
            name='RiskSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('category', models.CharField(choices=[('gst_mismatch', 'GST Mismatch'), ('duplicate_invoice', 'Duplicate Invoice'), ('unusual_amount', 'Unusual Amount'), ('late_payment', 'Late Payment'), ('vendor_risk', 'Vendor Risk'), ('compliance_gap', 'Compliance Gap'), ('cash_flow_risk', 'Cash-Flow Risk'), ('custom', 'Custom')], max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='open', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('confidence', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.PositiveIntegerField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ai_reasoning', models.JSONField(blank=True, default=dict, help_text='Raw AI model output / chain-of-thought.')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_signals', to='intelligence.customer')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='firms.firm')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_signals', to='intelligence.vendor')),
            ],
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['firm', 'name'], name='intelligenc_firm_id_50a521_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('gstin__gt', ''), ('is_deleted', False)), fields=('firm', 'gstin'), name='uq_customer_firm_gstin'),
        ),
        migrations.AddIndex(
            model_name='financialsnapshot',
            index=models.Index(fields=['firm', 'snapshot_type', '-snapshot_date'], name='intelligenc_firm_id_fb59ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('firm', 'snapshot_type', 'snapshot_date'), name='uq_snapshot_firm_type_date'),
        ),
        migrations.AddIndex(
            model_name='reconciliationlink',
            index=models.Index(fields=['firm', 'match_group'], name='intelligenc_firm_id_e8a3a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('transaction', 'matched_transaction'), name='uq_reconciliation_pair'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['firm', 'name'], name='intelligenc_firm_id_de65ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(condition=models.Q(('gstin__gt', ''), ('is_deleted', False)), fields=('firm', 'gstin'), name='uq_vendor_firm_gstin'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['firm', 'txn_date'], name='intelligenc_firm_id_8be0f3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['firm', 'txn_type', 'status'], name='intelligenc_firm_id_55e0ef_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['firm', 'vendor'], name='intelligenc_firm_id_0e4f90_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['firm', 'customer'], name='intelligenc_firm_id_afa2d1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_number'], name='intelligenc_referen_bb8f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='risksignal',
            index=models.Index(fields=['firm', 'status', 'severity', '-created_at'], name='idx_risk_dashboard'),
        ),
        migrations.AddIndex(
            model_name='risksignal',
            index=models.Index(fields=['firm', 'category', 'status'], name='idx_risk_category'),
        ),
        migrations.AddIndex(
            model_name='risksignal',
            index=models.Index(fields=['entity_type', 'entity_id'], name='idx_risk_entity'),
        ),
        migrations.AddIndex(
            model_name='risksignal',
            index=models.Index(fields=['firm', 'created_at'], name='idx_risk_timeline'),
        ),
    ]
