# Generated by Django 5.1.15 on 2026-08-19 09:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0001_initial'),
        ('intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('purchase_order', 'Purchase Order'), ('bank_statement', 'Bank Statement'), ('contract', 'Contract'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note')], max_length=30)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=1000)),
                ('file_size', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('needs_review', 'Needs Review'), ('verified', 'Verified'), ('approved', 'Approved'), ('extraction_failed', 'Extraction Failed')], default='processing', max_length=50)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('extraction_raw_json', models.TextField(blank=True, null=True)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('extraction_failed', models.BooleanField(default=False)),
                ('classified_type', models.CharField(blank=True, default='', max_length=30)),
                ('classification_confidence', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='firms.firm')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['firm', 'doc_type', 'status'], name='intelligenc_firm_id_4b8cec_idx'), models.Index(fields=['firm', 'uploaded_at'], name='intelligenc_firm_id_c4953e_idx')],
            },
        ),
    ]
