# Generated by Django 5.1.15 on 2026-08-19 09:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0001_initial'),
        ('intelligence', '0002_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_group', models.UUIDField(db_index=True, help_text='Links to the ReconciliationLink.match_group this exception belongs to.')),
                ('mismatch_cause', models.CharField(choices=[('bank_charges', 'Bank Charges / Fees'), ('discount', 'Discount Applied'), ('partial_payment', 'Partial Payment'), ('tax_deduction', 'TDS / Tax Deduction'), ('incorrect_payment', 'Incorrect Payment Amount'), ('duplicate', 'Possible Duplicate'), ('missing_counterpart', 'Missing Counterpart'), ('date_mismatch', 'Date Outside Tolerance'), ('vendor_mismatch', 'Vendor / Party Mismatch'), ('currency_mismatch', 'Currency Mismatch'), ('other', 'Other / Unknown')], max_length=30)),
                ('confidence', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Confidence in the diagnosed cause (0–1).', max_digits=5)),
                ('reason', models.TextField(help_text='Human-readable explanation of the mismatch.')),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved (Match Accepted)'), ('rejected', 'Rejected (Not a Match)'), ('adjusted', 'Adjusted Manually')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('candidate_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_recon_exceptions', to='intelligence.transaction')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='firms.firm')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_exceptions', to='intelligence.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['firm', 'review_status', '-created_at'], name='idx_recon_exc_review'), models.Index(fields=['firm', 'mismatch_cause'], name='idx_recon_exc_cause'), models.Index(fields=['match_group'], name='idx_recon_exc_group')],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('exact_matches', models.PositiveIntegerField(default=0)),
                ('fuzzy_matches', models.PositiveIntegerField(default=0)),
                ('exceptions_created', models.PositiveIntegerField(default=0)),
                ('unmatched', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Tolerance settings used for this run.')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='firms.firm')),
            ],
            options={
                'indexes': [models.Index(fields=['firm', '-started_at'], name='intelligenc_firm_id_1f5270_idx')],
            },
        ),
    ]
