# Generated by Django 5.1.15 on 2026-08-19 10:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0001_initial'),
        ('intelligence', '0003_reconciliationexception_reconciliationrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Composite 0–100 score.', max_digits=5)),
                ('payment_history', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('avg_payment_time_trend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('credit_exposure', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('revenue_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='Per-metric evidence and reasoning.')),
                ('previous_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('last_computed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='intelligence.customer')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='firms.firm')),
            ],
            options={
                'indexes': [models.Index(fields=['firm', '-overall_score'], name='idx_customer_score_rank')],
            },
        ),
        migrations.CreateModel(
            name='VendorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Composite 0–100 score.', max_digits=5)),
                ('invoice_consistency', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('payment_history', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('price_stability', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('document_quality', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('bank_change_frequency', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('anomaly_history', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='Per-metric evidence and reasoning.')),
                ('previous_score', models.DecimalField(blank=True, decimal_places=2, help_text='Score before the last recomputation (for delta display).', max_digits=5, null=True)),
                ('last_computed_at', models.DateTimeField(blank=True, null=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='firms.firm')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='intelligence.vendor')),
            ],
            options={
                'indexes': [models.Index(fields=['firm', '-overall_score'], name='idx_vendor_score_rank')],
            },
        ),
    ]
