# Generated by Django 5.1.15 on 2026-08-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eway_bills', '0002_ewaybillrecord_be_number_and_more'),
        ('firms', '0003_firm_base_currency'),
        ('intelligence', '0004_customerscore_vendorscore'),
        ('invoices', '0005_excelexportbatch'),
        ('trade_docs', '0002_alter_importexportrecord_container_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=10)),
                ('to_currency', models.CharField(max_length=10)),
                ('rate_date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('source', models.CharField(default='open_er_api', max_length=100)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='reconciliationlink',
            name='fx_difference',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Realised FX gain/loss locked when the settlement is recorded.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationlink',
            name='original_base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original transaction amount converted at the original transaction-time rate.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationlink',
            name='settled_at',
            field=models.DateTimeField(blank=True, help_text='When the settlement snapshot was captured.', null=True),
        ),
        migrations.AddField(
            model_name='reconciliationlink',
            name='settlement_base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Settlement leg amount converted at the settlement-time rate.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationlink',
            name='settlement_currency',
            field=models.CharField(blank=True, default='', help_text='Currency in which the settlement leg occurred.', max_length=10),
        ),
        migrations.AddField(
            model_name='reconciliationlink',
            name='settlement_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text="Settlement-date FX rate from settlement currency into the firm's base currency.", max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='base_currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='base_currency_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Functional/base-currency amount locked at transaction time.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text="Transaction-date FX rate from currency into the firm's base currency.", max_digits=18, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['firm', 'currency', 'txn_date'], name='intelligenc_firm_id_4488b7_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['from_currency', 'to_currency', '-rate_date'], name='idx_fx_pair_date'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('from_currency', 'to_currency', 'rate_date'), name='uq_fx_pair_date'),
        ),
    ]
