# Generated by Django 5.1.15 on 2026-08-19 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0003_firm_base_currency'),
        ('intelligence', '0005_exchangerate_reconciliationlink_fx_difference_and_more'),
        ('trade_docs', '0002_alter_importexportrecord_container_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risksignal',
            name='category',
            field=models.CharField(choices=[('gst_mismatch', 'GST Mismatch'), ('duplicate_invoice', 'Duplicate Invoice'), ('unusual_amount', 'Unusual Amount'), ('late_payment', 'Late Payment'), ('vendor_risk', 'Vendor Risk'), ('compliance_gap', 'Compliance Gap'), ('cash_flow_risk', 'Cash-Flow Risk'), ('trade_value_mismatch', 'Trade Value Mismatch'), ('payment_before_shipment', 'Payment Before Shipment Realization'), ('custom', 'Custom')], max_length=30),
        ),
        migrations.CreateModel(
            name='TradeFinanceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('partial', 'Partial (some legs missing)'), ('complete', 'Complete'), ('flagged', 'Flagged for Review')], default='partial', max_length=20)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('invoice_currency', models.CharField(blank=True, default='', max_length=10)),
                ('customs_declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('customs_currency', models.CharField(blank=True, default='', max_length=10)),
                ('value_difference', models.DecimalField(blank=True, decimal_places=2, help_text='invoice_amount − customs_declared_value (same currency).', max_digits=18, null=True)),
                ('value_difference_pct', models.DecimalField(blank=True, decimal_places=4, help_text='Percentage deviation: abs(diff) / customs_declared_value.', max_digits=7, null=True)),
                ('expected_shipment_date', models.DateField(blank=True, null=True)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('payment_before_shipment', models.BooleanField(default=False, help_text='True when payment_due_date < expected_shipment_date.')),
                ('analysis_notes', models.JSONField(blank=True, default=list)),
                ('last_analysed_at', models.DateTimeField(blank=True, null=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='firms.firm')),
                ('invoice_txn', models.ForeignKey(blank=True, help_text='The commercial invoice transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_finance_inv_links', to='intelligence.transaction')),
                ('payment_txn', models.ForeignKey(blank=True, help_text='The payment transaction settling this deal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_finance_pay_links', to='intelligence.transaction')),
                ('purchase_order_txn', models.ForeignKey(blank=True, help_text='The Purchase Order transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_finance_po_links', to='intelligence.transaction')),
                ('trade_doc', models.ForeignKey(blank=True, help_text='Bill of Entry / Shipping Bill.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_finance_links', to='trade_docs.importexportrecord')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_finance_links', to='intelligence.vendor')),
            ],
            options={
                'indexes': [models.Index(fields=['firm', 'status', '-created_at'], name='idx_tfl_status'), models.Index(fields=['firm', 'vendor'], name='idx_tfl_vendor')],
            },
        ),
    ]
