# Generated by Django 4.2.30 on 2026-06-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpverification_email_otpverification_purpose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRateLimitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('verify_attempt', 'Verify Attempt'), ('verify_failure', 'Verify Failure'), ('issue_otp', 'Issue OTP'), ('resend_otp', 'Resend OTP')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'ip_address', 'timestamp'], name='accounts_ot_event_t_c819f0_idx'), models.Index(fields=['event_type', 'email', 'timestamp'], name='accounts_ot_event_t_bc9226_idx')],
            },
        ),
    ]
