# Generated by Django 4.2.30 on 2026-06-30 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('bill', 'Bill'), ('import_export_record', 'Import-Export Record'), ('eway_bill_record', 'E-Way Bill Record')], max_length=40)),
                ('resource_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('edit', 'Edit'), ('delete', 'Delete'), ('verify', 'Verify'), ('export', 'Export'), ('retry_extraction', 'Retry Extraction')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('firm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='firms.firm')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['firm', 'resource_type', 'timestamp'], name='audit_audit_firm_id_effb6f_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx')],
            },
        ),
    ]
