# Generated by Django 5.1.15 on 2026-08-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_firm_access_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='resource_type',
            field=models.CharField(choices=[('bill', 'Bill'), ('import_export_record', 'Import-Export Record'), ('eway_bill_record', 'E-Way Bill Record'), ('document', 'Document')], max_length=40),
        ),
    ]
