# Generated by Django 5.1.15 on 2026-08-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('upload', 'Upload'), ('edit', 'Edit'), ('delete', 'Delete'), ('verify', 'Verify'), ('export', 'Export'), ('retry_extraction', 'Retry Extraction'), ('approve_agent_action', 'Approve Agent Action'), ('reject_agent_action', 'Reject Agent Action')], max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_type',
            field=models.CharField(choices=[('bill', 'Bill'), ('import_export_record', 'Import-Export Record'), ('eway_bill_record', 'E-Way Bill Record'), ('document', 'Document'), ('agent_approval', 'Agent Approval')], max_length=40),
        ),
    ]
