# Generated by Django 5.2.15 on 2026-06-30 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportExportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=1000)),
                ('file_size', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('needs_review', 'Needs Review'), ('verified', 'Verified'), ('extraction_failed', 'Extraction Failed')], default='processing', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('extraction_raw_json', models.TextField(blank=True, null=True)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('extraction_failed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('be_number', models.CharField(blank=True, max_length=100, null=True)),
                ('be_date', models.DateField(blank=True, null=True)),
                ('port_code', models.CharField(blank=True, max_length=20, null=True)),
                ('container_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('assessable_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('shipper_name', models.CharField(blank=True, max_length=255, null=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_docs', to='firms.firm')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_trade_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
