# Generated by Django 5.1.15 on 2026-08-19 10:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('finance', 'Finance Agent'), ('compliance', 'Compliance Agent'), ('cfo', 'CFO Agent'), ('audit', 'Audit Agent')], max_length=20)),
                ('query', models.TextField(help_text="The user's original question.")),
                ('response', models.JSONField(blank=True, default=dict, help_text='Evidence-Based AI structured response.')),
                ('routed_by', models.CharField(default='auto', help_text='How the agent was selected: auto | explicit.', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_conversations', to='firms.firm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_input', models.JSONField(default=dict)),
                ('tool_result', models.JSONField(default=dict)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='agents.agentconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_action', models.CharField(help_text="e.g. 'flag_transaction', 'send_reminder', 'update_risk_status'", max_length=100)),
                ('action_params', models.JSONField(default=dict)),
                ('reason', models.TextField(help_text="Agent's justification for the proposed action.")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('audit_log_id', models.PositiveIntegerField(blank=True, help_text='AuditLog.id created after approval execution.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_approvals', to='agents.agentconversation')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firms.firm')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentconversation',
            index=models.Index(fields=['firm', 'agent_type', '-created_at'], name='agents_agen_firm_id_75fdda_idx'),
        ),
        migrations.AddIndex(
            model_name='agentconversation',
            index=models.Index(fields=['user', '-created_at'], name='agents_agen_user_id_b4d360_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingapproval',
            index=models.Index(fields=['firm', 'status', '-created_at'], name='agents_pend_firm_id_ccfdc3_idx'),
        ),
    ]
