# Generated by Django 5.1.15 on 2026-08-19 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('firms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconversation',
            name='latency_ms',
            field=models.PositiveIntegerField(default=0, help_text='Total response time in ms.'),
        ),
        migrations.AddField(
            model_name='agentconversation',
            name='turn_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='firms.firm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_active_at'],
            },
        ),
        migrations.AddField(
            model_name='agentconversation',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Links this turn to a multi-turn session for follow-up context.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='agents.chatsession'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['firm', 'user', '-last_active_at'], name='agents_chat_firm_id_db4435_idx'),
        ),
    ]
