import logging

from django.conf import settings
from django.core import signing
from django.utils import timezone
from rest_framework import authentication, exceptions

from .models import User

logger = logging.getLogger(__name__)

class SignedTokenAuthentication(authentication.BaseAuthentication):
    """
    Custom authentication class that validates the cryptographically signed token
    generated by the OTP verification view.
    """
    def authenticate(self, request):
        auth_header = request.headers.get('Authorization')
        if not auth_header:
            return None

        parts = auth_header.split()
        if len(parts) != 2:
            return None

        scheme, token = parts[0], parts[1]
        if scheme.lower() not in ['bearer', 'token']:
            return None

        try:
            # Decode the signed token
            payload = signing.loads(token, key=settings.SECRET_KEY)

            # Check expiration
            exp_timestamp = payload.get('exp_timestamp')
            if exp_timestamp and timezone.now().timestamp() > exp_timestamp:
                raise exceptions.AuthenticationFailed('Token has expired.')

            user_id = payload.get('user_id')
            if not user_id:
                raise exceptions.AuthenticationFailed('Invalid token payload.')

            try:
                user = User.objects.get(id=user_id, is_active=True)
            except User.DoesNotExist:
                raise exceptions.AuthenticationFailed('No active user associated with this token.')

            return (user, token)

        except signing.BadSignature:
            raise exceptions.AuthenticationFailed('Invalid cryptographic token signature.')
        except exceptions.AuthenticationFailed:
            raise
        except Exception as e:
            logger.error("Token authentication failed: %s", e)
            raise exceptions.AuthenticationFailed('Token authentication error.')
