# Generated by Django 5.2.15 on 2026-06-30 08:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Invalid GSTIN format. Must be a valid 15-character Indian GSTIN (e.g., 27AAAAA1111A1Z1).', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('owner_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('active', 'Active')], default='pending_verification', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_firms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
