# Generated by Django 5.1.15 on 2026-08-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='jurisdiction',
            field=models.CharField(choices=[('IN', 'India (GST / E-Invoice)'), ('US', 'United States (Sales Tax / 1099)')], default='IN', help_text='Tax jurisdiction that selects the active compliance adapter.', max_length=5),
        ),
    ]
