# Generated by Django 5.1.15 on 2026-08-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0002_firm_jurisdiction'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='base_currency',
            field=models.CharField(default='INR', help_text='Functional/home currency used for reporting and FX conversion.', max_length=10),
        ),
    ]
